config/routes.rb
App::Application.routes.draw do

get "/"                              => "main#index",              as: "home_page"
get "/main/full_image"               => "main#full_image",         as: "full_image" 
get "/main/about"                    => "main#about"
get "/main/contact"                  => "main#contact"
get "/main/:id"                      => "main#product_category",   as: "category" 
get "/main/more_info/:id"            => "main#more_info_id"


get "/user"                     => "user#index",                  as: "user_signin"
post "/user/sign_in"            => "user#sign_in",                as: "user_signin1"
get "/user/new"                 => "user#new"
post "/user"                    => "user#create"
get "/user/email"               => "user#email",                  as: "email"
put "/user/send_email"          => "user#send_email",             as: "send_email"
get "/user/reset"               => "user#reset"                  
put "/user/reset"               => "user#reset_password",         as: "reset_password"
get "/user/ship_bill_info"      => "user#ship_bill_info",         as: "ship_info"  
put "/user/ship_bill_info_put"  => "user#update_ship",            as: "ship_update" 
get "/user/:id/edit"            => "user#edit",                   as: "user_edit"
put "/user/:id"                 => "user#update_user",            as: "user_update"
get "/user/orders"              => "user#user_orders",            as: "last_order"
post "/user/orders"             => "user#past_order",              as: "find_order"       
get "/user/logout"              => "user#logout"

get "/admin"                  => "admin#index",                     as: "admin_signin"
post "/admin/signin"          => "admin#signin",                    as: "admin_signedin"
get "/admin/links"            => "admin#links",                     as: "links"
get "/admin/orders"           => "admin#view_orders",               as: "view_orders"
get "/admin/new"              => "admin#new",                       as: "new_product"
post "/admin"                 => "admin#create",                    as: "new_product1"
get "/admin/:id/edit"         => "admin#edit",                      as: "edit_product"
put "/admin/:id"              => "admin#update",                    as: "edit_product1"
get "/admin/product_sale"     => "admin#product_sale",              as: "/product_sale"
post "/admin/product_sale/"   => "admin#product_sale_edit_post",    as: "/product_sale1" 
get "/admin/category_sale/"   => "admin#category_sale_edit",        as: "/category_sale"
post "/admin/category_sale/"  => "admin#category_sale_edit_post",   as: "/category_sale1"  
get "/admin/logout"           => "admin#logout"
get "/admin/form"             => "admin#form",                      as: "form"
post "/admin/upload"          => "admin#upload_image",              as: "upload"
get  "/admin/images/:id.:ext" => "admin#image_data",                as: "image_data"

get "/carts/final_cart"       => "carts#final_cart",                as: "final_cart"
put "/carts/place_order"      => "carts#place_order",               as: "place_order"
resources :carts

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    render :index and return
  end

  def product_category
    product_category = Category.find(params[:id]).name
    @header = "#{product_category}"
    @products = Product.where(category: product_category)
    render :show and return
  end

  def more_info_id
    id = params[:id]
    @header = "Product Detail Page"
    @product = Product.find_by(id: id)
    render :more_info and return
  end

  def about
    render :about and return
  end

  def contact
    render :contact and return
  end
  
  def full_image 
    render :full_image, layout: false and return
  end

end

app/helpers/main_helper.rb
module MainHelper

def flash_alert (x)
 if flash[:"#{x}"] != nil
  "<div class='alert alert-#{x}'>
    #{flash[:"#{x}"]}
  </div>".html_safe
  end
end

def add_to_cart (p)
#   if p.quantity > 0
#     "<h5 class='pad'>#{label_tag :quantity}
#     #{text_field_tag "quantity_#{p.id}", 1, size: 1}
#     #{button_tag 'Add to cart', name: 'product_id', value: p.id}</h5>".html_safe
#   else
#     "<p class='pad' style='font-size: 14pt; color: black;'>
#       <i>This item is currently out of stock.</i></p>".html_safe
#   end
end

def image_display (p)
  if Image.find_by(name: p.product_code) == nil
      "<a href='/images/#{p.image}_big.jpg/'>
        <img class='zoomin_img zoomin_img:hover image' src='/images/#{p.image}.jpg/' width='250' height='187'></img>
      </a>".html_safe
  else
    image = Image.find_by(name: p.product_code)
      "<a href='/images/#{p.image}.jpg/'>
        <img class='image' src='#{image_data_path(image.id, image.extension)}' width='250' height='187'>
       </a>".html_safe
  end 
end

def pad_sizes
   [
    ['50', '0050'],
    ['100', '0100'],
    ['200', '0200'],
    ['400', '0400'],
    ['800', '0800'],
    ['1500', '1500'],
    ['3000', '3000'],
  ]
end


end

app/views/main/about.html.erb
<%= form_tag "/main/about" do %>
<h2>This is the about us page</h2>
<% end %>

app/views/main/contact.html.erb
<div class='pull-left contact'>
  <%= image_tag('store_front.jpg') %>
</div>
<div>  
  <h3 style='color: rgba(6, 72, 133, 0.85);'>For ordering or information call</h3>
  <h3 style='color: rgba(6, 72, 133, 0.85);'> (720) 363-0163</h3>
  <h4 style='color: rgba(6, 72, 133, 0.85);'><em> This is a mobile business offering delivery and tool service to most of Colorado!</em></h4>
  <h3 style='color: white;'>We are located at:</h3>
  <h3 style='color: white;'>50 Rio Grande Blvd, Denver CO</h3>
  <h4 style='color: white;'><em>Tool Showroom hours: 8am to 4pm - Monday through Friday</em></h4>
</div>

app/views/main/full_image.html.erb
<div class="full_image" class="container">
  <img src='/images/pp4-acp-0050_big.jpg'>
</div>

app/views/main/index.html.erb
<%= form_tag carts_path, method: "POST" do %>

<h4 style='color: white;'><em>Note: this website is under construction, 
only a small precentage of products available are currently displayed</em><h4>

<div class="row">
  <div class="col-md-12">
    <h1><p class="ats_header_c">On Sale This Month...</p1></h1>
  </div>
</div>

<div class="row">
  <%= render partial: "layouts/index_product" %>
</div>

<center>
  <h3 class="shadow">Come visit our showroom to view our selection of sinks,<br>
     stone tools and supplies at:</h3>
  <h3 style="color: #550808">50 Rio Grande Blvd, Denver CO</h3>
  <h4>Or call 720-363-0163 to place an order</h4>
</center>

<% if session[:username] != "" %>
  <% user = User.find_by(username: session[:username]) %>
    <% if user != nil %>
      <% user_name = user.username %>
    <% else %>
      <% user_name = "new" %>
    <% end %>
    <% if user_name == "wendy" %>
      <a href="/admin">Admin Links</a>
    <% end %>
<% end %>
  
<% end %>

app/views/main/more_info.html.erb
<%= form_tag carts_path do %>

<div class="pad_col">
  <div class="row">
    <div class="col-md-12">
      <center><b><h3 class="pad" style="color: #550808; text-shadow: 2px 1px 1px white;">
                    <%= @product.name.upcase %></h3></b>
      </center>
      <table> 
        <th>
          <a href='/images/<%= @product.image %>_big.jpg/'>
            <img class="image_big" src="/images/<%= @product.image %>.jpg/"></img>
          </a>
        </th>
        <td><p class="pad" style="color: rgb(9, 9, 145); background: white;"><%= @product.more_info %></p>
            <h4 class="pad" style="color=black"><i>price  </i>$<%= "%.2f" % @product.price %></h4>
            <% CategorySale.where(category_id: @product.category_id).each do |s| %>
              <% if s.percent_off > 1 %>
                <% price = (@product.price) * ((100-s.percent_off)/100) %>
                  <h4 class="sale_price""><%= "Sale Price! $ #{"%.2f" % price}" %></h4>
              <% else %>
                <% if @product.percent_off > 1 %>
                  <% price = (@product.price) * ((100-@product.percent_off)/100) %>
                  <h4 class="sale_price"><%= "Sale Price! $ #{"%.2f" % price}" %></h4>
                <% end %>
              <% end %>
            <% end %>
            <%= add_to_cart (@product) %>
        </td>
      </table>             
    </div>         
  </div>
</div>

<% end %>

app/views/main/show.html.erb
<%= form_tag carts_path, method: "POST" do %>

<div class="ats_header_b">
  <%= @header %>
</div>

<div pull-right>
<div class="pad_col row">
<% @products.each do |p| %>
  <div class="col-md-12" >
    <table>       
      <td><p class="pad"><%= image_display (p) %></pad></td>
      <td><b><h3 class="pad" style="color: #550808; text-shadow: 2px 1px 1px white;"><%= p.name.titlecase %></h3></b>
        <b><center><p style="color=black"><i>price  </i>$<%= "%.2f" % p.price %></p></center></b>
        <% CategorySale.where(category_id: p.category_id).each do |sale| %>
          <% if sale.percent_off > 1 %>
            <% price = (p.price) * ((100 - sale.percent_off)/100) %>
              <p class="sale_price"><%= "Sale Price! $ #{"%.2f" % price}" %></p>
              <h4 class="pad" style="color: black"><%= p.description.capitalize %></h4>
              <h5><a class="pad" href="/main/more_info/<%= p.id %>" style="color: rgba(6, 72, 133, 0.85)">
                More details and applications...</a></h5>
              <%= add_to_cart (p) %>
          <% else %>
            <% if p.percent_off > 1 %>
              <% price = (p.price) * ((100-p.percent_off)/100) %>
              <p class="sale_price"><%= "Sale Price! $ #{"%.2f" % price}" %></p>
              <h4 class="pad" style="color: black"><%= p.description.capitalize %></h4>
              <h5><a class="pad" href="/main/more_info/<%= p.id %>" style="color: rgba(6, 72, 133, 0.85)">
                More details and applications...</a></h5>
              <%= add_to_cart (p) %>
            <% else %> 
              <h4 class="pad" style="color: black"><%= p.description.capitalize %></h4>
              <h5><a class="pad" href="/main/more_info/<%= p.id %>" style="color: rgba(6, 72, 133, 0.85)">
                More details and applications...</a></h5>
              <%= add_to_cart (p) %>
            <% end %>
          <% end %>   
        </td>
        <hr style="background-color:white;height:2px;border:none;" />
      </table>  
      <% end %> 
</div> 
<% end %>
</div>
</div>    
                     
<% end %>