config/routes.rb
App::Application.routes.draw do

get "/"                              => "main#index",              as: "home_page"
get "/main/full_image"               => "main#full_image",         as: "full_image" 
get "/main/about"                    => "main#about"
get "/main/contact"                  => "main#contact"
get "/main/:id"                      => "main#product_category",   as: "category" 
get "/main/more_info/:id"            => "main#more_info_id"


get "/user"                     => "user#index",                  as: "user_signin"
post "/user/sign_in"            => "user#sign_in",                as: "user_signin1"
get "/user/new"                 => "user#new"
post "/user"                    => "user#create"
get "/user/email"               => "user#email",                  as: "email"
put "/user/send_email"          => "user#send_email",             as: "send_email"
get "/user/reset"               => "user#reset"                  
put "/user/reset"               => "user#reset_password",         as: "reset_password"
get "/user/ship_bill_info"      => "user#ship_bill_info",         as: "ship_info"  
put "/user/ship_bill_info_put"  => "user#update_ship",            as: "ship_update" 
get "/user/:id/edit"            => "user#edit",                   as: "user_edit"
put "/user/:id"                 => "user#update_user",            as: "user_update"
get "/user/orders"              => "user#user_orders",            as: "last_order"
post "/user/orders"             => "user#past_order",              as: "find_order"       
get "/user/logout"              => "user#logout"

get "/admin"                  => "admin#index",                     as: "admin_signin"
post "/admin/signin"          => "admin#signin",                    as: "admin_signedin"
get "/admin/links"            => "admin#links",                     as: "links"
get "/admin/orders"           => "admin#view_orders",               as: "view_orders"
get "/admin/new"              => "admin#new",                       as: "new_product"
post "/admin"                 => "admin#create",                    as: "new_product1"
get "/admin/:id/edit"         => "admin#edit",                      as: "edit_product"
put "/admin/:id"              => "admin#update",                    as: "edit_product1"
get "/admin/product_sale"     => "admin#product_sale",              as: "/product_sale"
post "/admin/product_sale/"   => "admin#product_sale_edit_post",    as: "/product_sale1" 
get "/admin/category_sale/"   => "admin#category_sale_edit",        as: "/category_sale"
post "/admin/category_sale/"  => "admin#category_sale_edit_post",   as: "/category_sale1"  
get "/admin/logout"           => "admin#logout"
get "/admin/form"             => "admin#form",                      as: "form"
post "/admin/upload"          => "admin#upload_image",              as: "upload"
get  "/admin/images/:id.:ext" => "admin#image_data",                as: "image_data"

get "/carts/final_cart"       => "carts#final_cart",                as: "final_cart"
put "/carts/place_order"      => "carts#place_order",               as: "place_order"
resources :carts

end

app/views/admin/category_sale.html.erb
<%= render "layouts/admin" %>
<%= form_tag "/admin/category_sale" do %>
<% if @error != nil %>
  <h2 style="color: blue"><%= @error %></h2>
<% end %>

<div class="pad">
  <h3 style="color: white"> Edit Category of Product on Sale </h3>
<div class="row">
  <div class="col-md-6">
    <h3>
      <%= label_tag "category_name", "Product category on sale" %><br>
      <%= select_tag "category_name", options_from_collection_for_select(CategorySale.order(:id),
       :category_name, :category_name), prompt: "Choose product category..." %><br></br>
  
      <%= label_tag "percent_off", "Enter the percentage off "%><h5><i>(if taking off sale enter 0)<i></h5><br>
      <%= text_field_tag "percent_off", "", size: 4 %>%<br></br>

      <%= submit_tag "Submit", size: 40 %>
    </h3>  
  </div> 
</div>
</div>
<% end %>

app/views/admin/edit_product.html.erb
<%= render "layouts/admin" %>
<%= form_tag "/admin/:id", method: "PUT" do %>


<% if @error != nil %>
  <h2 style="color: rgb(156, 18, 18)"><%= @error %></h2>
<% end %>

<div class="pad">
<h1 style="color: rgba(51, 51, 51, 0.67)"><%= label_tag "product_code", "Select the product to edit" %><br><h1>
  <%= select_tag :product_id, options_from_collection_for_select(
      Product.order(:id), :id, :product_code, @old_product.id), 
      prompt: "Choose product, then click edit" %>
    <%= submit_tag "Select", size: 20 %><br>
</div>

<hr style="color: white">   
<div class="pad">
<div class="row">
  <div class="col-md-4" style="color: rgba(51, 51, 51, 0.67)">
    <h3>
      <%= label_tag "category", "Product Category" %><br>
      <%= select_tag "category", options_for_select([
      "Diamond Products", "Safety Equipment", "Abrasives", "Glues & Sealer",
      "Pads", "Other Products"], @old_product.category), prompt: "Choose product category..." %><br></br>

  
      <%= label_tag "product_code", "Product Code" %><br>
      <%= text_field_tag "product_code", @old_product.product_code, size: 20 %><br></br>

      <%= label_tag "name", "Name" %><br>
      <%= text_field_tag "name", @old_product.name, size: 20 %><br></br>     
    </h3>
  </div>
  <div class="col-md-4" style="color: rgba(51, 51, 51, 0.67)">
    <h3>
      <%= label_tag "quantity", "Quantity" %><br>
      <%= text_field_tag "quantity", @old_product.quantity, size: 20 %><br></br>
      
      <%= label_tag :more_info, "More Info" %><br>
      <%= text_area_tag :more_info, @old_product.more_info, size: 20 %><br></br>
      
      <%= label_tag "description", "Description" %><br>
      <%= text_area_tag "description", @old_product.description, size: 20 %><br></br>

      <%= label_tag "price", "Price" %><br>
      <%= text_field_tag "price", @old_product.price, size: 20 %><br></br>
      
        <%= submit_tag "Update" %>
        <%= submit_tag "Delete" %>
    </h3>  
  </div> 
</div>
</div>
<% end %>

app/views/admin/form.html.erb
<%= render "layouts/image_admin" %>

<table class="table">
  <tr>
    <th>ID</th>
    <th>Image</th>
    <th>Uploaded at</th>
  </tr>
  <% Image.order(:id).each do |image| %>
    <tr>
      <td><%= image.id %></td>
      <td><img height="50"
        src="<%= image_data_path(image.id, image.extension) %>"></td>
      <td><%= image.created_at %></td>
    </tr>
  <% end %>
</table>

<%= form_tag upload_path, multipart: true, class: "dropzone",
      id: "image-upload", style: "min-height:inherit; height:200px" do %>
  <div class="fallback">
    <%= file_field_tag :file, multiple: true %>
    <%= submit_tag "Upload" %>
  </div>
<% end %>

<script>
  Dropzone.options.imageUpload = {
    //forceFallback: true, // uncomment to test uploading without Dropzone
    dictFallbackMessage: "Choose an image to upload...",
    success: function() { window.location.reload(); }
  };
</script>

app/views/admin/index.html.erb
<%= render "layouts/admin" %>

<%= form_tag admin_signedin_path do %>

<div class="pad">
<div class="row">
  <div class="col-md-6">
  <h4> Enter username and password </h4>
    <h3>
      <%= label_tag "username", "" %><br>
      <%= text_field_tag "username", "", size: 20 %><br>

      <%= label_tag "password", "" %><br>
      <%= password_field_tag %> 
    </h3>
  </div>
    </div> 
      </h3>  
      
      <%= submit_tag "Sign in", size: 40 %>
</div>
</div>

<% end %>

app/views/admin/links.html.erb
<%= render "layouts/admin" %>
<ul>
  <h2><li><a style="color: rgba(3, 3, 100, 0.8)" href="/admin/orders">view orders for shipping</a></li><br>
      <li><a style="color: #927017" href="/admin/new">add a new product</a></li>
      <li><h2 style="color: #927017"><%= link_to "edit and existing product", edit_product_path(Product.first) %></h2></li>
      <li><a style="color: #1E5A53" href="/admin/product_sale">put a single product on sale</a></li><br>
      <li><a style="color: #1E5A53" href="/admin/category_sale">put an entire category on sale</a></li><br>
      <li><a style="color: #550808" href="/admin/form">upload an image</a></li>
  </h2>
</ul>

app/views/admin/new_product.html.erb
<%= render "layouts/admin" %>
<%= form_tag new_product1_path do %>

<% if @error != nil %>
  <h2 style="color: blue"><%= @error %></h2>
<% end %>

<div class="row">
  <div class="col-md-4" style="color: rgba(3, 3, 100, 0.8)">
    <h2 style="color: white"> Add New Product </h2>
    <h3>
      <%= label_tag :category, "Product Category" %><br>
      <%= select_tag "category", options_for_select([
      "Diamond Products", "Safety Equipment", "Abrasives", "Glues & Sealer",
      "Pads", "Other Products"]), prompt: "Choose product category..." %><br></br>

      <%= label_tag "product_code", "Product Code" %> <i style="color: white">
      (Testing: use "abc-12<b style="color: rgba(159, 118, 341, 200)">3</b>"
      <b style="color: rgba(159, 118, 341, 200)"> ...4,5,6</b>)</i><br>
      <%= text_field_tag "product_code", "", placeholder: "abc-123", size: 20 %><br></br>
     

      <%= label_tag "name", "Name" %><br>
      <%= text_field_tag "name", "", placeholder: "name", size: 20 %><br></br> 
      
      <%= label_tag "more_info", "More Infomation, Details and Applications" %><br>
      <%= text_area_tag "more_info", "", placeholder: "info", size: 20 %><br></br>   
    </h3>
  </div>
  <div class="col-md-3" style="color: rgba(3, 3, 100, 0.8)">
    <h3>
      <%= label_tag "quantity", "Quantity" %><br>
      <%= text_field_tag "quantity", "", placeholder: "quantity", size: 20 %><br></br>
  
      <%= label_tag "description", "Description" %><br>
      <%= text_area_tag "description", "", placeholder: "description", size: 100 %><br></br>
  
      <%= label_tag "price", "Price" %><br>
      <%= text_field_tag "price", "", placeholder: "price", size: 20 %><br></br>
      <%= submit_tag "Submit" %>
    </h3> 
  </div>
</div>
<% end %>

app/views/admin/product_sale.html.erb
<%= render "layouts/admin" %>
<%= form_tag "/admin/product_sale" do %>
<% if @error != nil %>
  <h2 style="color: blue"><%= @error %></h2>
<% end %>

<div class="pad">
  <h2> Edit Product on Sale </h2>
<div class="row">
  <div class="col-md-3">
    <h3>
      <%= label_tag "product_code", "Product on sale" %><br>
      <%= select_tag "product_code", options_from_collection_for_select(Product.order(:id),
       :product_code, :product_code), prompt: "Choose product..." %><br></br>
  
      <%= label_tag "percent_off", "Enter the percentage off "%><h5><i>(if taking off sale enter 0)<i></h5><br>
      <%= text_field_tag "percent_off", "", size: 4 %>%<br></br>

      <%= submit_tag "Submit", size: 40 %>
    </h3>  
  </div> 
</div>
</div>
<% end %>

app/views/admin/view_orders.html.erb
<%= render "layouts/admin" %>
<div class="row">
<div class="col-md-12">
  <table class="table" style="background: white">
  <% old_value = 0 %>
  <% Order.order(:created_at).reverse.each do |get_number| %>
    <% if get_number.order_number != old_value && old_value != nil %>
      <% new_order_number = get_number.order_number %>
      <% old_value = get_number.order_number %>
    <% else %>
      <% new_order_number = nil %>
      <% old_value = get_number.order_number %>
    <% end %>
    <% if new_order_number != nil %>
      <% orders = Order.where(order_number: new_order_number) %>
      <% customer = User.find(orders.last.user_id) %>
      <td><hr style="background-color:black;height:3px;border:none;" />
         <b>Customer:</b><br>
         <%= customer.shipping_first_name %>
         <%= customer.shipping_last_name %><br>
         <%= customer.shipping_address1 %>
         <%= customer.shipping_address2 %></br>
         <%= customer.shipping_city %>
         <%= customer.shipping_state %>
         <%= customer.shipping_zip %></br>
         <%= customer.shipping_phone_number %></td>
      <td><hr style="background-color:black;height:3px;border:none;" />
        <b>order number:</b><br></br> 
        <%= orders.last.order_number%><br></br>
        <b>date:</b> <%= orders.last.created_at.getlocal.strftime("%A - %B %d, %Y -- %I:%M %p %Z") %></td>
      <tr><th>Products</th></tr>
        <% orders.order(:id).each do |o| %>
          <% if o.product_id != nil %>
            <tr>
              <td><%= Product.find(o.product_id).name %></td>
              <td><%= o.quantity %> <i>qty</i><br></br>
                  $<%= "%.2f" % o.price_paid_for_product %> price of each</td>
            <tr> 
          <% end %>
        <% end %> 
          <tr><td><%= "<b>tax</b>: $#{"%.2f" % orders.last.tax} <b>ship_cost</b>: $#{"%.2f" % orders.last.ship_cost} 
          <b>total</b>: $#{"%.2f" % orders.last.order_total}".html_safe %></td></tr>
    <% end %>
  <% end %>
  </table>
</div>
</div>
 
  
      
       
      
      
      
      
      
      