config/routes.rb
App::Application.routes.draw do

get "/"                              => "main#index",              as: "home_page"
get "/main/full_image"               => "main#full_image",         as: "full_image" 
get "/main/about"                    => "main#about"
get "/main/contact"                  => "main#contact"
get "/main/:id"                      => "main#product_category",   as: "category" 
get "/main/more_info/:id"            => "main#more_info_id"


get "/user"                     => "user#index",                  as: "user_signin"
post "/user/sign_in"            => "user#sign_in",                as: "user_signin1"
get "/user/new"                 => "user#new"
post "/user"                    => "user#create"
get "/user/email"               => "user#email",                  as: "email"
put "/user/send_email"          => "user#send_email",             as: "send_email"
get "/user/reset"               => "user#reset"                  
put "/user/reset"               => "user#reset_password",         as: "reset_password"
get "/user/ship_bill_info"      => "user#ship_bill_info",         as: "ship_info"  
put "/user/ship_bill_info_put"  => "user#update_ship",            as: "ship_update" 
get "/user/:id/edit"            => "user#edit",                   as: "user_edit"
put "/user/:id"                 => "user#update_user",            as: "user_update"
get "/user/orders"              => "user#user_orders",            as: "last_order"
post "/user/orders"             => "user#past_order",              as: "find_order"       
get "/user/logout"              => "user#logout"

get "/admin"                  => "admin#index",                     as: "admin_signin"
post "/admin/signin"          => "admin#signin",                    as: "admin_signedin"
get "/admin/links"            => "admin#links",                     as: "links"
get "/admin/orders"           => "admin#view_orders",               as: "view_orders"
get "/admin/new"              => "admin#new",                       as: "new_product"
post "/admin"                 => "admin#create",                    as: "new_product1"
get "/admin/:id/edit"         => "admin#edit",                      as: "edit_product"
put "/admin/:id"              => "admin#update",                    as: "edit_product1"
get "/admin/product_sale"     => "admin#product_sale",              as: "/product_sale"
post "/admin/product_sale/"   => "admin#product_sale_edit_post",    as: "/product_sale1" 
get "/admin/category_sale/"   => "admin#category_sale_edit",        as: "/category_sale"
post "/admin/category_sale/"  => "admin#category_sale_edit_post",   as: "/category_sale1"  
get "/admin/logout"           => "admin#logout"
get "/admin/form"             => "admin#form",                      as: "form"
post "/admin/upload"          => "admin#upload_image",              as: "upload"
get  "/admin/images/:id.:ext" => "admin#image_data",                as: "image_data"

get "/carts/final_cart"       => "carts#final_cart",                as: "final_cart"
put "/carts/place_order"      => "carts#place_order",               as: "place_order"
resources :carts

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :products
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

before_action :send_home

#    before_action :set_cart, only: [:show, :edit, :update, :destroy]
#    before_action  :check_quantity, only: [:create, :update]
#    before_action  :product_quantity_update, only: [:create] 
  
  def index
    @carts = Cart.where(cart_id: session[:cart_id])
    if @carts.first == nil
      @empty = "yes"
    end
  end
  
  def show
  end

#   def new
#     @cart = Cart.new
#   end
# 
#   def edit
#   end

  def create 
    @product = Product.find(params[:product_id])
    if params["quantity_#{@product.id}"].to_i < 1
      c_id = Category.find_by(name: @product.category).id
      flash[:danger] = "Please enter a positive number for quantity"
      redirect_to "/main/#{c_id}" and return
    end
      if Cart.find_by(product_id: params[:product_id], cart_id: session[:cart_id]) != nil
        c_id = Category.find_by(name: @product.category).id
        flash[:info] = "#{@product.name.titlecase} has already been added to the cart.
                        The product's quantity can be adjusted in the cart."
        redirect_to "/main/#{c_id}" and return 
      else
        session[:cart_id]   = params[:authenticity_token]
        @cart               = Cart.new#(cart_params)
        @cart.cart_id       = params[:authenticity_token]
        @cart.product_id    = params[:product_id]
        @cart.quantity      = params["quantity_#{@product.id}"].to_i
        category_percent_off = CategorySale.find_by(category_id: @product.category_id).percent_off
        if @product.percent_off <= category_percent_off
          price = @product.price * ((100-category_percent_off)/100)
        else
          price = @product.price * ((100-@product.percent_off)/100)
        end
        @cart.price         = price
        respond_to do |format|
        if @cart.save
          flash[:success] = "#{@product.name.titlecase} has been added to the cart"
          c_id = Category.find_by(name: @product.category).id
          @product.quantity = @product.quantity - @cart.quantity
          @product.save!
          redirect_to "/main/#{c_id}" and return
          format.json { render action: 'show', status: :created, location: @cart }
          #format.html { render action: 'new' }
          #format.json { render json: @cart.errors, status: :unprocessable_entity }
        end
      end   
    end
  end
  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    @product = Product.find(params[:product_id])
    if params["quantity_#{@product.id}"].to_i < 0
      flash[:danger] = "Please enter a positive number for quantity or 0"
      redirect_to carts_path and return
    end
    old_cart = Cart.find_by(product_id: params[:product_id], cart_id: session[:cart_id])
    @product = Product.find(params[:product_id])
    @cart = Cart.find_by(product_id: params[:product_id], cart_id: session[:cart_id])
    @cart.quantity = params["quantity_#{@product.id}"].to_i
    if @cart.quantity == 0
      @product.quantity = @product.quantity.to_i + (old_cart.quantity.to_i - @cart.quantity.to_i)
      @product.save!
      @cart.delete
      redirect_to carts_path and return
    end
    if @cart.quantity.to_i >= old_cart.quantity.to_i
      @product.quantity = @product.quantity.to_i - (@cart.quantity.to_i - old_cart.quantity.to_i)
    else
      @product.quantity = @product.quantity.to_i + (old_cart.quantity.to_i - @cart.quantity.to_i)
    end
    @product.save!
     if @cart.save == true  #(cart_params)
      @carts = Cart.where(cart_id: session[:cart_id])
      render :index and return
      #format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
      #format.json { head :no_content }
    else
      flash[:danger] = "There was an error"
      redirect_to home_page_path and return
      #format.html { render action: 'edit' }
      #format.json { render json: @cart.errors, status: :unprocessable_entity }
    end
  end

  def final_cart
      @carts = Cart.where(cart_id: session[:cart_id])
      render :final_cart and return
  end
  
  def place_order
    if Cart.find_by(cart_id: session[:cart_id]) == nil
      flash[:danger] = "There is nothing in the cart to order"
      redirect_to home_page_path and return
    end
  
    #ActiveMerchant accepts all amounts as Integer values in cents
    amount = 1000  # $10.00

    # The card verification value is also known as CVV2, CVC2, or CID
    credit_card = ActiveMerchant::Billing::CreditCard.new(
                    :first_name         => params[:credit_first_name],
                    :last_name          => params[:credit_last_name],
                    :number             => params[:credit_number],
                    :month              => params[:credit_month],
                    :year               => params[:credit_year],
                    :verification_value => params[:credit_security_code],)
       
    # Validating the card automatically detects the card type
    if credit_card.valid?
    #Capture $10 from the credit card
    gateway = ActiveMerchant::Billing::TrustCommerceGateway.new(
            :login => 'TestMerchant',
            :password => 'password')
   
      response = gateway.purchase(amount, credit_card)
   
      if response.success?
          order_number = Order.last.id + 777
          Cart.all.each do |cart|
            Order.create! order_number: order_number, user_id: User.find_by(username: session[:username]).id, 
            product_id: cart.product_id, price_paid_for_product: cart.price, quantity: cart.quantity
            cart.delete
          end
          Order.create! order_number: order_number, user_id: User.find_by(username: session[:username]).id,
           tax: params[:tax], ship_cost: params[:ship_cost], order_total: params[:order_total]
           total_order = Order.where(order_number: order_number, user_id: User.find_by(username: session[:username]).id)
           order = Order.find_by(order_number: order_number, user_id: User.find_by(username: session[:username]))
           user = User.find_by(username: session[:username])
           total_amount = params[:order_total] 
           product_names =  total_order.collect do |p|
             if p.product_id != nil
               product_names=["#{Product.find(p.product_id).name}, price of each: $ #{"%.2f" % p.price_paid_for_product}, qty: #{p.quantity}        "'<br></br>'"^"]
             end
           end
           product_names.pop
           link = last_order_url(user.id, order.order_number)
      #     <br></br>Sign into account and click this link 
      #     <a href='#{link}'>View Last Order</a> to view most recent order.
      #{last_order_url}
          Pony.mail(
           to:        user.email_address,
           subject:   "Action Tool & Supply LLC order receipt",
           body:      "To view order online sign into your account, click your account link, 
                        and click the view orders link. Enter #{order.order_number}
                        Order#: #{order.order_number}",
           html_body: test = "<b>Action Tool & Supply LLC</b>
                          <br></br>50 Rio Grande Blvd, Denver CO
                          <br></br>720-363-0163<br></br>
                          Order#: #{order.order_number}
                          <hr>
                          <br></br>Shipped to:
                          <br></br>           #{user.shipping_address1} #{user.shipping_address2}
                          <br></br>           #{user.shipping_city}, #{user.shipping_state} #{user.shipping_zip}
                          <br></br>Date: #{order.created_at.strftime('%-m/%-d/%y')} Time: #{order.updated_at.getlocal.strftime('%I:%M %p %Z')}
                          <hr>
                          <br></br>Products:<br></br>
                          <br></br>#{product_names.join(" ").split("^").join}
                          <br></br>Shipping: $#{"%.2f" % params[:ship_cost]}
                          <br></br>Taxes: $#{"%.2f" % params[:tax]}
                          <br></br><h4>Order Total: $#{"%.2f" % total_amount}</h4>
                          <h3>Thank you for your order.</h3><br></br>
                          <i>(To view this order or another online, sign into your account, click your account link, 
                             and click the view orders link.)</i><br></br>".html_safe 
           )
          flash[:info] = "Your order has been charged to the credit card #{credit_card.display_number} Thank you. A receipt has been e-mailed to: #{user.email_address}."
          Cart.where(cart_id: session[:cart_id]).each do |c|
            c.delete
          end
          redirect_to home_page_path and return 
        end        
      else
        @carts = Cart.where(cart_id: session[:cart_id])
        flash.now[:danger] = "Please try entering your credit card info again."
        render :final_cart and return
      end
    end
  
  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end

  private
  
  def check_quantity
    product = Product.find(params[:product_id])
    if params["quantity_#{product.id}"].to_i > product.quantity && params[:button] == "update"
      @carts = Cart.where(cart_id: session[:cart_id])
      flash.now[:info] = "We apologize, the quantity can only be increased by <b style='color: rgba(3, 3, 100, 0.8)'>#{product.quantity.to_i}</b>
      or less of product <b>#{product.name}</b>, at this time".html_safe
      render :index and return
      elsif
        params["quantity_#{product.id}"].to_i > product.quantity
        flash[:info] = "We apologize, only <b style='color: rgba(3, 3, 100, 0.8)'>#{product.quantity.to_i}</b>
          or less of product <b>#{product.name}</b>, can be ordered at this time".html_safe
        c_id = Category.find_by(name: product.category).id
        redirect_to "/main/#{c_id}" and return
    else

app/helpers/carts_helper.rb
module CartsHelper
#   def add_to_cart (x)
#     "<h5 class='pad'>
#         #{label_tag :quantity}
#         #{text_field_tag :quantity, 1, size: 1}
#         #{button_tag "Add to cart", name: 'product_id', value: "#{x}"}
#      </h5>".html_safe
#   end
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :ship_method %><br>
    <%= f.text_field :ship_method %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/final_cart.html.erb
<%= form_tag place_order_path, method: "PUT" do %>
<h2 style="color: rgba(3, 3, 100, 0.8)">Product List</h2>
<div class="row pad">
<div class="col-md-6 pull-left">
  <table class="table-condensed table-striped table-border">
    <thead>
      <tr>
        <th style="color: white">Product Name</th>
        <th style="color: white">Price</th>
        <th style="color: white">Quantity</th>
      </tr>
    </thead>
    <tbody>
      <% session[:total] = 0 %>
      <% @carts.each do |cart| %>
      <% p = Product.find(cart.product_id) %>
        <tr>
          <% if cart.quantity != 0 %>
            <td><%= p.name.titleize %></td>
            <td style="text-align: right">$<%= "%.2f" % cart.price %></td>
            <td style="text-align: right"><h4><%= cart.quantity %></h4></td>
          <% end %>
            <% if @carts != false %>
            <% session[:total] += cart.price * cart.quantity %>
            <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="col-md-4">
  <table class="table-condensed">
    <% products_total = session[:total] %>
      <tr><td><h4 style="color: rgba(6, 72, 133, 0.85); text-align: right;">
        <%= "Products total:    $#{"%.2f" % products_total}" %>
      </h4></td></tr>
    <% if @empty == "yes" %>  
      <% ship_cost = 0 %>
    <% else %>
      <% ship_cost = 7 %>
      <%= hidden_field_tag "ship_cost", ship_cost %>
    <% end %>
      <tr><td><h4 style="color: rgba(6, 72, 133, 0.85); text-align: right;">
        <%= "Shipping cost:    $#{"%.2f" % ship_cost}" %>
      </h4></td></tr>
    <% tax = products_total * 0.029 %>
    <%= hidden_field_tag "tax", tax %>
      <tr><td><h4 style="color: rgba(6, 72, 133, 0.85); text-align: right;">
        <%= "Taxes:    $#{"%.2f" %  tax}" %></td></tr>
      <tr><td><h4 style="color: rgba(3, 3, 100, 0.8); text-align: right;"><b>
        <% order_total = ship_cost + tax + products_total %>
        <%= "Order total:    $#{"%.2f" % (order_total)}" %>
        <%= hidden_field_tag "order_total", order_total %>
      </b></h4></td></tr></h4>
  </table>   
</div>

<div class="pad pull-left">
<hr style="background-color:white; height:2px;" />
  <h4>(During this testing phase, if you want the transaction 
      to complete use credit info already entered)
  <h4 style="color: white">Enter payment information as it is shown on card::<h4>
  <h5>
    <div class="col-md-6 pull-left">
     <% if User.find_by(username: session[:username]) == "bob" %>
     <%= label_tag :credit_number, "Credit Card Number" %>
     <%= text_field_tag :credit_number,'4242424242424242' %><br></br>
     <%= label_tag :credit_month, "Month of Expiration" %>
        <%= select_tag :credit_month, user.credit_month, 
            prompt: "" %><br></br>
     <%= label_tag :credit_year, "Year of Expiration" %>
     <%= text_field_tag :credit_year, '2015', size: 5 %><br></br>
    </div>
    <div class="col-md-3 pull-right">
        <%= label_tag :credit_first_name, "First Name" %>
        <%= text_field_tag :credit_first_name, user.credit_first_name %><br></br>
        <%= label_tag :credit_last_name, "Last Name" %>
        <%= text_field_tag :credit_last_name, user.credit_last_name %><br></br>
        <%= label_tag :credit_security_code, "Security Code" %>
        <%= text_field_tag :credit_security_code, user.credit_security_code %>
    </div>
      <% else %>
    <div class="col-md-7 pull-left">
       <%= label_tag :credit_number, "Credit Card Number" %>
       <%= text_field_tag :credit_number,'4242424242424242' %><br></br>
       <%= label_tag :credit_month, "Month of Expiration" %>
          <%= select_tag :credit_month, options_for_select(months, 8), 
              prompt: "" %><br></br>
       <%= label_tag :credit_year, "Year of Expiration" %>
       <%= text_field_tag :credit_year, '2015', size: 5 %><br></br>
    </div>
    <div class="col-md-5 pull-right">
        <%= label_tag :credit_first_name, "First Name" %>
        <%= text_field_tag :credit_first_name,'Bob' %><br></br>
        <%= label_tag :credit_last_name, "Last Name" %>
        <%= text_field_tag :credit_last_name, 'Bobsen' %><br></br>
        <%= label_tag :credit_security_code, "Security Code" %>
        <%= text_field_tag :credit_security_code, '000' %>
     </div> 
      <% end %>
  </h5>
 </div>
</div>
<center>
  <input class="btn btn-danger" name="Place Order" type="submit" value="Place Order"><br></br>
</center>
<% end %>

app/views/carts/index.html.erb
<%= @test %>
<%= form_tag "/carts/1", method: "PATCH" do %>
<h2 style="color: rgba(3, 3, 100, 0.8)">Product List</h2>
<div class="row pad">
<div class="col-md-6 pull-left">
  <table class="table-condensed table-striped table-border">
    <thead>
      <tr>
        <th>Product Name</th>
        <th>Price</th>
        <th style="text-align: right">Quantity</th>
      </tr>
    </thead>
    <tbody>
      <% session[:total] = 0 %>
      <% @carts.each do |cart| %>
      <% p = Product.find(cart.product_id) %>
        <tr>
          <% if cart.quantity != 0 %>
            <td><%= p.name.titleize %></td>
            <td style="text-align: right">$<%= "%.2f" % cart.price %></td>
            <td style="text-align: right"><h4><%= text_field_tag "quantity_#{p.id}", cart.quantity, size: 1 %></h4></td>
            <td><h5><%= button_tag "update", name: "product_id", value: p.id %></h5></td>
            <%= hidden_field_tag "button", "update" %>
          <% end %>
            <% if @carts != false %>
            <% session[:total] += cart.price * cart.quantity %>
            <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="col-md-4">
  <table class="table-condensed">
    <% products_total = session[:total] %>
      <tr><td><h4 style="color: rgba(6, 72, 133, 0.85); text-align: right;">
        <%= "Products total:    $#{"%.2f" % products_total}" %>
      </h4></td></tr>
    <% if @empty == "yes" %>  
      <% ship_cost = 0 %>
    <% else %>
      <% ship_cost = 7 %>
    <% end %>
      <tr><td><h4 style="color: rgba(6, 72, 133, 0.85); text-align: right;">
        <%= "Shipping cost:    $#{"%.2f" % ship_cost}" %>
      </h4></td></tr>
    <% tax = products_total * 0.029 %>
      <tr><td><h4 style="color: rgba(6, 72, 133, 0.85); text-align: right;">
        <%= "Taxes:    $#{"%.2f" %  tax}" %></td></tr>
      <tr><td><h4 style="color: rgba(3, 3, 100, 0.8); text-align: right;"><b>
        <%= "Order total:    $#{"%.2f" % (ship_cost + tax + products_total)}" %>
      </b></h4></td></tr></h4>
  </table><br>
        <%= link_to 'Continue Shopping', home_page_path %><br><br>
        <%= link_to 'Checkout', ship_info_path %><br><br>
</div>
  <div class="col-md-2 pull-right">  
  </div>
</div>
<% end %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @cart.product_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @cart.quantity %>
</p>

<p>
  <strong>Ship method:</strong>
  <%= @cart.ship_method %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>