config/routes.rb
App::Application.routes.draw do

get "/"                              => "main#index",              as: "home_page"
get "/main/full_image"               => "main#full_image",         as: "full_image" 
get "/main/about"                    => "main#about"
get "/main/contact"                  => "main#contact"
get "/main/:id"                      => "main#product_category",   as: "category" 
get "/main/more_info/:id"            => "main#more_info_id"


get "/user"                     => "user#index",                  as: "user_signin"
post "/user/sign_in"            => "user#sign_in",                as: "user_signin1"
get "/user/new"                 => "user#new"
post "/user"                    => "user#create"
get "/user/email"               => "user#email",                  as: "email"
put "/user/send_email"          => "user#send_email",             as: "send_email"
get "/user/reset"               => "user#reset"                  
put "/user/reset"               => "user#reset_password",         as: "reset_password"
get "/user/ship_bill_info"      => "user#ship_bill_info",         as: "ship_info"  
put "/user/ship_bill_info_put"  => "user#update_ship",            as: "ship_update" 
get "/user/:id/edit"            => "user#edit",                   as: "user_edit"
put "/user/:id"                 => "user#update_user",            as: "user_update"
get "/user/orders"              => "user#user_orders",            as: "last_order"
post "/user/orders"             => "user#past_order",              as: "find_order"       
get "/user/logout"              => "user#logout"

get "/admin"                  => "admin#index",                     as: "admin_signin"
post "/admin/signin"          => "admin#signin",                    as: "admin_signedin"
get "/admin/links"            => "admin#links",                     as: "links"
get "/admin/orders"           => "admin#view_orders",               as: "view_orders"
get "/admin/new"              => "admin#new",                       as: "new_product"
post "/admin"                 => "admin#create",                    as: "new_product1"
get "/admin/:id/edit"         => "admin#edit",                      as: "edit_product"
put "/admin/:id"              => "admin#update",                    as: "edit_product1"
get "/admin/product_sale"     => "admin#product_sale",              as: "/product_sale"
post "/admin/product_sale/"   => "admin#product_sale_edit_post",    as: "/product_sale1" 
get "/admin/category_sale/"   => "admin#category_sale_edit",        as: "/category_sale"
post "/admin/category_sale/"  => "admin#category_sale_edit_post",   as: "/category_sale1"  
get "/admin/logout"           => "admin#logout"
get "/admin/form"             => "admin#form",                      as: "form"
post "/admin/upload"          => "admin#upload_image",              as: "upload"
get  "/admin/images/:id.:ext" => "admin#image_data",                as: "image_data"

get "/carts/final_cart"       => "carts#final_cart",                as: "final_cart"
put "/carts/place_order"      => "carts#place_order",               as: "place_order"
resources :carts

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :email_address, presence: true
  validates :email_address, uniqueness: true
  validates :email_address, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/ }

  has_secure_password
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController

before_action :send_home, only: [:ship_bill_info, :update_ship, :user_orders, :past_order]
before_action :check_user, only: [:edit, :update]

def index
  if params[:page] != nil
    @product = Product.find(params[:page])
  end
  render :index and return
end

def sign_in
  if params[:commit] == "Create account"
    render :new and return
  end
   
  if User.find_by(username: params[:username])== nil
      flash[:danger] = "Username was entered incorrectly or doesn't exist. 
                        <i style='color: gray'>If you haven't done so already, please create an account below.</i>".html_safe
    render :index and return
  else
      user = User.find_by(username: params[:username]) 
    if user.authenticate(params[:password]) != false 
      session[:username] = user.username
      flash[:info] = "You are logged in as: <b>#{user.username}</b>".html_safe
      redirect_to "/" and return
    else
      flash.now[:danger] = "Please enter the correct password"
      render :index and return
    end
  end
end

def email
  render :email and return
end

def send_email
  session[:email] = params[:email]
  user = User.find_by(email_address: session[:email])
  link = reset_password_url(user.id, user.email_verification_token)
    Pony.mail(
      to:        session[:email],
      subject:   "Reset Password Link",
      body:      "If the link below doesn't work you can copy and paste this url: #{link}.",
      html_body: "Please click this link  <b>#{link}</b> to reset your password."
    )
  flash.now[:info] = "An e-mail has been sent, please use the link provided to reset
                      your password."
  render :email and return
end

def reset
  render :reset and return
end

def reset_password
  user = User.find_by(email_address: session[:email])
  user.password               = params[:password]
  user.password_confirmation  = params[:password_confirmation] 
  if user.password == user.password_confirmation
    user.save!
    flash[:info] = "Your password has been updated"
    redirect_to user_signin_path and return
  else
    flash.now[:danger] = "Both passwords must match."
    render :reset and return
  end
end

def edit
  @old_user = User.find_by(username: session[:username])
  render :edit and return
end

def update_user
  if params[:commit] == "Update Username"
    edit_user = User.find_by(username: session[:username])
    edit_user.username = params[:username]
    session[:username] = edit_user.username
    if edit_user.save == true
      redirect_to home_page_path and return
    else
      flash.now[:danger] = "Username is already taken, please try another"
      @old_user = User.find_by(username: session[:username])
      render :edit and return
    end
   elsif params[:commit] == "Update E-mail"
      edit_user = User.find_by(username: session[:username])
      edit_user.email_address = params[:email_address]
     if edit_user.save == true
      redirect_to home_page_path and return
    else
      flash.now[:danger] = "An account with that e-mail already exists"
      @old_user = User.find_by(username: session[:username])
      render :edit and return
    end
  else
    @old_user = User.find_by(username: session[:username])
    edit_user = User.find_by(username: session[:username])
    edit_user.username = params[:username]
    edit_user.password = params[:password]
    edit_user.password_confirmation =  params[:password_confirmation]
    if edit_user.password_confirmation != edit_user.password
      flash.now[:danger] = "There was a problem with the passwords, they must be entered and match.
                           Please try again."
      render :edit and return
    else
      if edit_user.save != false
        flash[:warning] = "Your password has been updated"
        redirect_to home_page_path and return
      end
    end
  end
end

def new
  @user = User.new
  render :new and return
end

def create
  @user = User.new
  @user.username = params[:username]
  if @user.username == ""
    flash.now[:danger] = "Username can not be blank. Please try again."
    render :new and return
    elsif
      User.find_by(username: @user.username) != nil
      flash.now[:danger] = "Username already exists. Please try again." 
      render :new and return
  end
    @user.password = params[:password]
    @user.password_confirmation = params[:password_confirmation]
  if @user.password_confirmation != @user.password
    flash.now[:danger] = "There was a problem with the passwords, they must be entered and match.
                      Please try again."
    render :new and return
  end
    @user.email_address = params[:email_address]
  if @user.email_address == ""
    flash.now[:danger] = "Please enter an e-mail address."
    render :new and return
  end
  if @user.save == true
     session[:username] = @user.username 
     flash[:info] = "You are logged in as: <b>#{@user.username}</b>".html_safe
     redirect_to "/" and return
  else
    if User.find_by(email_address: @user.email_address) != nil
      flash.now[:danger] = "The e-mail address entered already exists. Please try again." 
      render :new and return
      else
    flash.now[:danger] = "The e-mail entered is invalid, please try again."
    render :new and return
    end
  end
end

def ship_bill_info
  if Cart.find_by(cart_id: session[:cart_id]) == nil
      flash[:danger] = "There is nothing in the cart to order"
      redirect_to home_page_path and return
    end
  if session[:username] == nil
    flash.now[:info] = "Please sign in or create account and return to view cart."
    render :index and return
  else
    @user = User.find_by(username: session[:username])
  end
end

def update_ship
  if params[:commit] == "yes"
    session[:bill_same] = params[:commit]
    @user = User.find_by(username: session[:username])
    flash.now[:warning] = "Please enter or update shipping information, if needed.
                        <i>Then continue.</i>".html_safe
    render :ship_bill_same and return
  elsif params[:commit] == "no"
    session[:bill_same] = params[:commit]
    @user = User.find_by(username: session[:username])
    flash.now[:warning] = "Please enter or update shipping and billing information, if needed.
                    <i>Then continue.</i>".html_safe
    render :ship_bill_info and return
  end
    edit_user = User.find_by(username: session[:username])
    edit_user.company_name          = params[:company_name]
    edit_user.shipping_first_name   = params[:shipping_first_name]
    edit_user.shipping_last_name    = params[:shipping_last_name]
    edit_user.shipping_address1     = params[:shipping_address1]
    edit_user.shipping_address2     = params[:shipping_address2]
    edit_user.shipping_city         = params[:shipping_city]
    edit_user.shipping_state        = params[:shipping_state]
    edit_user.shipping_zip          = params[:shipping_zip]
    edit_user.shipping_phone_number = params[:shipping_phone_number]
  if session[:bill_same] == "yes"
    edit_user.billing_first_name    = params[:shipping_first_name]
    edit_user.billing_last_name     = params[:shipping_last_name]
    edit_user.billing_address1      = params[:shipping_address1]
    edit_user.billing_address2      = params[:shipping_address2]
    edit_user.billing_city          = params[:shipping_city]
    edit_user.billing_state         = params[:shipping_state]
    edit_user.billing_zip           = params[:shipping_zip]
    edit_user.billing_phone_number  = params[:shipping_phone_number]
  else
    edit_user.billing_first_name    = params[:billing_first_name]
    edit_user.billing_last_name     = params[:billing_last_name]
    edit_user.billing_address1      = params[:billing_address1]
    edit_user.billing_address2      = params[:billing_address2]
    edit_user.billing_city          = params[:billing_city]
    edit_user.billing_state         = params[:billing_state]
    edit_user.billing_zip           = params[:billing_zip]
    edit_user.billing_phone_number  = params[:billing_phone_number]
  end
    edit_user.save!
  if params[:shipping_address1] == "" || params[:shipping_zip]  == "" 
       flash.now[:danger] = "Street address, city, state and zip code information is required."
       @user = User.find_by(username: session[:username])
       render :ship_bill_info and return
    elsif params[:shipping_city] == "" || params[:shipping_state]  == "" 
      flash.now[:danger] = "Street address, city, state and zip code information is required."
      @user = User.find_by(username: session[:username])
      render :ship_bill_info and return
  end 
    redirect_to final_cart_path and return
end

def user_orders
  @past_order = Order.where(user_id: User.find_by(username: session[:username]).id).last
  render :orders and return
end

def past_order
  @past_order = Order.find_by(order_number: params[:order_number])
  render :orders and return
end

def logout
  flash[:warning] = "You have been logged out. Come visit our showroom located at <b>50 Rio Grande Blvd, Denver CO</b>.".html_safe
    Cart.where(cart_id: session[:cart_id]).each do |c|
      @product = Product.find_by(id: c.product_id)
      @product.quantity = @product.quantity.to_i + c.quantity
      @product.save!
      c.delete
      end
    session.clear
  redirect_to "/" and return
end

  private
  
  def send_home
    redirect_to '/'
  end
  
  def check_user
    if session[:username] == nil
      redirect_to '/'
    end
  end


end

app/views/user/edit.html.erb
<%= form_tag user_update_path, method: "PUT" do %>

<% if @error != nil %>
  <h2 style="color: rgb(156, 18, 18)"><%= @error %></h2>
<% end %>

<hr style="color: white">   
<div class="pad">
<div class="row">
  <div class="col-md-4">
    <h3 style="color: rgba(6, 72, 133, 0.85)">
      <%= label_tag "username", "Edit username" %><br>
      <%= text_field_tag "username", @old_user.username, size: 15 %></i><br></br>
      <input class="btn btn-primary" name="commit" type="submit" value="Update Username">
    </h3>
  </div>
  <div class="col-md-4">
    <h3 style="color: #927017">
      <%= label_tag "password", "New password" %><br>
      <%= password_field_tag "password", "", size: 15 %><br></br> 
      
      <%= label_tag "password_confirmation", "Enter new password again"%><br>
      <%= password_field_tag "password_confirmation", "", size: 15 %><br></br>     
    </h3>  
      <input class="btn btn-warning" name="commit" type="submit" value="Update Password">
  </div> 
  <div class="col-md-4">
    <h3 style="color: rgba(6, 72, 133, 0.85)">    
      <%= label_tag "email_address", "Enter new e-mail address"%><br>
      <%= text_field_tag "email_address", "", size: 20 %><br></br>     
    </h3>  
      <input class="btn btn-info" name="commit" type="submit" value="Update E-mail"><br></br>
      <a href="<%= last_order_path %>">View Last Order</a>
  </div> 
</div>
</div>
<% end %>

app/views/user/email.html.erb
<%= form_tag send_email_path, method: "PUT" do %>

<div class="pad">
<div class="row">
  <div class="col-md-6">
  <h4><i>Enter your e-mail address</i></h4>
    <h3>
      <%= label_tag :email, "e-mail address" %><br>
      <%= text_field_tag :email, "", size: 20 %><br>
    </h3>
  </div>
    </div> 
      <input class="btn btn-primary" name="commit" type="submit" value="Submit"><br></br>
    </div>
</div>

<% end %>

app/views/user/index.html.erb
<%= form_tag user_signin1_path do %>

<div class="pad">
<div class="row">
  <div class="col-md-6">
  <h4 style="color: rgba(6, 72, 133, 0.85)"><i>Enter username and password</i></h4>
    <h3 style="color: rgba(6, 72, 133, 0.85)">
      <%= label_tag :username %><br>
      <%= text_field_tag :username, "", size: 20 %><br>
      <%= label_tag :password %><br>
      <%= password_field_tag :password %> 
    </h3>
  </div>
    </div> 
      <input class="btn btn-primary" name="commit" type="submit" value="Sign in">
      <input class="btn btn-primary" name="commit" type="submit" value="Create account">
      <a href="/user/email">Forgot Password</a>
  </div>
</div>

<% end %>

app/views/user/new.html.erb
<%= form_tag "/user" do %>
<div class="pad">
  <h2> New Customer Sign Up </h2>
<div class="row">
  <div class="col-md-4">
    <h3>
      <%= label_tag "username" %><br>
      <%= text_field_tag "username"%><br></br>

      <%= label_tag "password" %><br>
      <%= password_field_tag "password"%><br></br></h3> 
    </div>        
 <div class="col-md-4">
      <h3><%= label_tag "password_confirmation" %><br>
          <%= password_field_tag "password_confirmation" %><br></br>
      
          <%= label_tag "email_address" %><br>
          <%= text_field_tag "email_address" %><br></br> 
      </h3> 
</div>
 <div class="col-md-4">
    <input class="btn btn-primary" name="commit" type="submit" value="Sign up">
  </div> 
</div>
</div>
<% end %>

app/views/user/orders.html.erb
<%= form_tag last_order_path do %>

Order number:
  <% if @past_order != nil %>
  <%= view_order_number = @past_order.order_number %>
  <% end %>

<table class="table">
  <tr>
    <th>Products</th>
    <th>Price</th>
    <th>Quantity</th>
  </tr>
  <% if view_order_number != nil %>
  <% Order.where(user_id: User.find_by(username: session[:username]).id, order_number:
    view_order_number).each do |o| %>
    <% if o.product_id != nil %>
      <tr>
        <td><%= Product.find(o.product_id).name %></td>
        <td>$<%= "%.2f" % o.price_paid_for_product %></td>
        <td><%= Order.find_by(order_number: view_order_number, product_id: o.product_id).quantity %></td>
      </tr>
    <% else %>
      <tr>
        <td>tax:</td>
        <td><i>$<%= "%.2f" % o.tax %></i></td>
      </tr>
      <tr>
        <td>shipping:</td>
        <td><i>$<%= "%.2f" % o.ship_cost %></i></td>
      </tr>
      <tr>
        <td><b>order total:</b></td>
        <td><b>$<%= "%.2f" % o.order_total %></b></td>
      </tr>
    <% end %>
  <% end %>
  <% end %>
</table>
  <%= label_tag :order_number, "To view a previous order, enter order number" %><br>
  <input class="input-sm" id="order_number" name="order_number" size="10" type="text" value="">
  <input class="btn btn-primary" name="commit" type="submit" value="Submit"><br></br>
<% end %>

app/views/user/reset.html.erb
<%= form_tag reset_password_path, method: "PUT" do %>

<div class="pad">
<div class="row">
  <div class="col-md-6">
    <h3>
      <%= label_tag "password", "New password" %><br>
      <%= password_field_tag "password", "", size: 20 %><br></br>     
      
      <%= label_tag "password_confirmation", "Enter new password again"%><br>
      <%= password_field_tag "password_confirmation", "", size: 20 %><br></br>     
    </h3>
  </div>
    </div> 
      <input class="btn btn-primary" name="commit" type="submit" value="Submit"><br></br>
    </div>
</div>

<% end %>

app/views/user/ship_bill_info.html.erb
<%= form_tag ship_update_path, method: "PUT" do %>

  <h4> Is your billing information then same as shipping?
  <%= submit_tag "yes" %>
  <%= submit_tag "no" %></h4>

  
<% if @error != nil %>
  <h2 style="color: rgb(156, 18, 18)"><%= @error %></h2>
<% end %>

<div class="row">
  <div class="col-md-5 pull-left">
    <h4 style="color: rgba(3, 3, 100, 0.8)">
     
        <%= label_tag "shipping_first_name", "First name" %><br>
        <%= text_field_tag "shipping_first_name", @user.shipping_first_name, size: 20 %><br></br>
      
        <%= label_tag "shipping_last_name", "Last name" %><br>
        <%= text_field_tag "shipping_last_name", @user.shipping_last_name, size: 20 %><br></br>
        
        <%= label_tag "company_name", "Company name" %><br>
        <%= text_field_tag "company_name", @user.company_name, size: 20 %><br></br>
      
        <%= label_tag "shipping_address1", "Street address" %><br>
        <%= text_field_tag "shipping_address1", @user.shipping_address1, size: 20 %><br></br>
      
        <%= label_tag "shipping_address2", "Street address (continued)" %><br>
        <%= text_field_tag "shipping_address2", @user.shipping_address2, size: 20 %><br></br>
      
        <%= label_tag "shipping_city", "City" %><br>
        <%= text_field_tag "shipping_city", @user.shipping_city, size: 20 %><br></br>
        
        <%= label_tag "shipping_state", "State" %><br>
        <%= select_tag :shipping_state, options_for_select(us_states, @user.billing_state), 
            prompt: "" %><br></br>
      
        <%= label_tag "shipping_zip", "Zip Code" %><br>
        <%= text_field_tag "shipping_zip", @user.shipping_zip, size: 20 %><br></br>
      
        <%= label_tag "shipping_phone_number", "Phone number" %><br>
        <%= text_field_tag "shipping_phone_number", @user.shipping_phone_number, size: 20 %><br></br>
    </h4> 
  </div>
  
  <div class="col-md-7 pull-right">
    <h4 style="color: #550808">
      
        <%= label_tag "billing_first_name", "First name" %><br>
        <%= text_field_tag "billing_first_name", @user.billing_first_name, size: 20 %><br></br>
      
        <%= label_tag "billing_last_name", "Last name" %><br>
        <%= text_field_tag "billing_last_name", @user.billing_last_name, size: 20 %><br></br>
      
        <%= label_tag "billing_address1", "Street address" %><br>
        <%= text_field_tag "billing_address1", @user.billing_address1, size: 20 %><br></br>
      
        <%= label_tag "billing_address2", "Street address (continued)" %><br>
        <%= text_field_tag "billing_address2", @user.billing_address2, size: 20 %><br></br>
      
        <%= label_tag "billing_city", "City" %><br>
        <%= text_field_tag "billing_city", @user.billing_city, size: 20 %><br></br>
      
        <%= label_tag "billing_state", "State" %><br>
        <%= select_tag :billing_state, options_for_select(us_states, @user.billing_state),
            prompt: "" %><br></br>
       
        <%= label_tag "billing_zip", "Zip Code" %><br>
        <%= text_field_tag "billing_zip", @user.billing_zip, size: 20 %><br></br>
      
        <%= label_tag "billing_phone_number", "Phone number" %><br>
        <%= text_field_tag "billing_phone_number", @user.billing_phone_number, size: 20 %><br></br>
    
        <%= submit_tag "Continue" %>
    </h4> 
  </div>
</div>

<% end %>

app/views/user/ship_bill_same.html.erb
<%= form_tag ship_update_path, method: "PUT" do %>

<% if @error != nil %>
  <h2 style="color: rgb(156, 18, 18)"><%= @error %></h2>
<% end %>

<div class="row pad">
  <div class="col-md-4 pull-left">
    <h4 style="color: rgba(3, 3, 100, 0.8)">
     
        <%= label_tag "shipping_first_name", "First name" %><br>
        <%= text_field_tag "shipping_first_name", @user.shipping_first_name, size: 20 %><br></br>
      
        <%= label_tag "shipping_last_name", "Last name" %><br>
        <%= text_field_tag "shipping_last_name", @user.shipping_last_name, size: 20 %><br></br>
      
        <%= label_tag "shipping_address1", "Street address" %><br>
        <%= text_field_tag "shipping_address1", @user.shipping_address1, size: 20 %><br></br>
      
        <%= label_tag "shipping_address2", "Street address (continued)" %><br>
        <%= text_field_tag "shipping_address2", @user.shipping_address2, size: 20 %><br></br>
  </div>
  <div class="col-md-4 pull-left">
    <h4 style="color: rgba(3, 3, 100, 0.8)">
        <%= label_tag "shipping_city", "City" %><br>
        <%= text_field_tag "shipping_city", @user.shipping_city, size: 20 %><br></br>
        
        <%= label_tag "shipping_state", "State" %><br>
        <%= select_tag :shipping_state, options_for_select(us_states, @user.billing_state) %><br></br>
      
        <%= label_tag "shipping_zip", "Zip Code" %><br>
        <%= text_field_tag "shipping_zip", @user.shipping_zip, size: 20 %><br></br>
      
        <%= label_tag "shipping_phone_number", "Phone number" %><br>
        <%= text_field_tag "shipping_phone_number", @user.shipping_phone_number, size: 20 %><br></br>
       
        <%= submit_tag "Continue" %>
    </h4> 
  </div>
</div>

<% end %>